### ISSUE TITLE
Unexpected error attempting to load Stream : "Scaling list config is not met in static image cases."

### ISSUE THREAD

**Issue by bpieslak** [fileformat-heic/FileFormat.HEIC-for-.NET#8]
I am attempting to convert an HEIC image to a PNG following the example code written here:
https://products.fileformat.dev/heic/net/
"Convert HEIC collection to a set of PNG files programatically in C#"

When I call `HeicImage.Load`, I encounter an exception 

"Scaling list config is not met in static image cases."
   at FileFormat.Heic.Decoder.scaling_list_data..ctor(BitStreamWithNalSupport stream)
   at FileFormat.Heic.Decoder.seq_parameter_set_rbsp..ctor(BitStreamWithNalSupport stream, UInt64 startPosition, Int32 size)
   at FileFormat.Heic.Decoder.NalUnit.ParseKnownUnit(BitStreamWithNalSupport stream, Int32 size, NalUnitType type)
   at FileFormat.Heic.Decoder.HEVCDecoderConfigurationRecord..ctor(BitStreamWithNalSupport stream)
   at FileFormat.Heic.Decoder.HeicImageFrame.LoadProperties(BitStreamWithNalSupport stream, List`1 properties)
   at FileFormat.Heic.Decoder.HeicImage.ReadFramesMeta(BitStreamWithNalSupport stream)
   at FileFormat.Heic.Decoder.HeicImage.Load(Stream stream)

I am using FileFormat.Heic.Decoder, Version=24.7.1.0  using a .NETStandard 2.0 library

[IMG_1063.zip](https://github.com/user-attachments/files/17100495/IMG_1063.zip)

**Comment by bpieslak** [comment]
For reference, if I pull down the latest code, and in `scaling_list_data.cs`, if I remove line 26

`throw new NotImplementedException("Scaling list config is not met in static image cases.");`

then I am able to load the attached IMG_1063 above and successfully convert the first frame to a PNG file.

Admittedly, I know **nothing** about the HEIC format, so I don't know why that `throw new NotImplementedException` was there to begin with or why my image works differently from the other images in the Test case samples folder.

I don't want to suggest removing that line without knowing why it was there to begin with, so is there a reason to throw that NotImplementException there, or would you consider removing it?

**Comment by Horodep** [comment]
We will research the provided file and the problem and consider removing it.

**Comment by Horodep** [comment]
@bpieslak 
Are you the author of the photo?
If yes, can we add it to the repository and use it in testing?

**Comment by bpieslak** [comment]
@Horodep 
Yes I am the author of the photo.
And yes, you have my permission to add it to the repository and use it in your testing.

**Comment by Horodep** [comment]
@bpieslak 
Fixed in 5b385dc89f1afcdf515c1f0c5c1d6b2e4c2840e6. Thank you for the feedback and the provided file.
